services:
  - type: web
    name: pdf-parser
    runtime: docker
    rootDir: pdf-parser
    dockerfilePath: ./Dockerfile
    plan: free
    region: virginia

  - type: web
    name: backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    region: virginia
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PDF_PARSER_URL
        fromService:
          name: pdf-parser
          type: web
          property: host
      - key: ACCESS_TOKEN_TTL
        value: 15m
      - key: REFRESH_TOKEN_TTL
        value: 7d
